---
primary:
  address: ":5010"
health:
  port: ":5011"
  endpoint: "/health"
pprof:
  address: ":5012"
metric:
  address: ":5013"
  metricsOptions:
    namespace: xmidt
    subsystem: caduceator
log:
  file: "stdout"
  level: "DEBUG"
  maxsize: 50
  maxage: 30
  maxbackups: 10
  json: true
vegetaConfig:
  frequency: 1
  period: "10s"
  connections: 500
  duration: 0
  maxRoutines: 0
  postURL: "http://caduceus:6000/api/v3/notify"
  sleepTime: "0s"
  clientTimeout: "15s"
  messages:
    fixedCurrentTime: true
    messageContents:
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/offline"
          metadata:
            - "/hw-model": "hardware1"
            - "/fw-name": "firmware2"
            - "/hw-last-reboot-reason": "reboot-reason-2"
          transactionUUID: "0"
        bootTimeOffset: "-13m"
        birthdateOffset: "-1m"
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/fully-manageable"
          metadata:
            - "/hw-model": "hardware1"
            - "/fw-name": "firmware1"
            - "/hw-last-reboot-reason": "reboot-reason-1"
          transactionUUID: "1"
        bootTimeOffset: "-10m"
        birthdateOffset: "-2m"
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/operational"
          metadata:
            - "/hw-model": "hardware1"
            - "/fw-name": "firmware1"
            - "/hw-last-reboot-reason": "reboot-reason-1"
          transactionUUID: "2"
        bootTimeOffset: "-10m"
        birthdateOffset: "-3m"
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/online"
          metadata:
            - "/hw-model": "hardware1"
            - "/fw-name": "firmware1"
            - "/hw-last-reboot-reason": "reboot-reason-1"
          transactionUUID: "3"
        bootTimeOffset: "-10m"
        birthdateOffset: "-4m"
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/offline"
          metadata:
            - "/hw-model": "hardware1"
            - "/fw-name": "firmware2"
            - "/hw-last-reboot-reason": "reboot-reason-2"
          transactionUUID: "4"
        bootTimeOffset: "-13m"
        birthdateOffset: "-14m"
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/reboot-pending/2s"
          metadata:
            - "/hw-model": "hardware1"
            - "/fw-name": "firmware2"
            - "/hw-last-reboot-reason": "reboot-reason-2"
          transactionUUID: "5"
        bootTimeOffset: "-13m"
        birthdateOffset: "-15m"
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/online"
          metadata:
            - "/hw-model": "hardware1"
            - "/fw-name": "firmware2"
            - "/hw-last-reboot-reason": "reboot-reason-2"
          transactionUUID: "6"
        bootTimeOffset: "-13m"
        birthdateOffset: "-16m"
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/offline"
          metadata:
            - "/hw-model": "hardware1"
            - "/fw-name": "firmware2"
            - "/hw-last-reboot-reason": "reboot-reason-2"
          transactionUUID: "7"
        bootTimeOffset: "-13m"
        birthdateOffset: "-17m"
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/online"
          metadata:
            - "/hw-model": "hardware1"
            - "/fw-name": "firmware2"
            - "/hw-last-reboot-reason": "reboot-reason-2"
          transactionUUID: "8"
        bootTimeOffset: "-13m"
        birthdateOffset: "-18m"
  # simulates talaria rehash
  vegetaRehash:
    routines: 0
    period: "1s"
    frequency: 500
    connections: 500
    duration: 0

# The following is an example Caduceator vegeta configuration to load test Caduceus
# of a slow consumer by sending 1000 events per second and only wanting Caduceator
# to be cutoff by Caduceus 5 times.

# vegetaConfig:
#     frequency: 1000,
#     period: "1s",
#     connections: 500,
#     duration : 0,
#     maxRoutines: 5,
#     sleepTime: "45s",
#     clientTimeout: "5s",
#     wrpMessageDest: "event:device-status/mac:112233445566/offline"

prometheusConfig:
  queryURL: "http://prometheus:9090/api/v1/query"
  queryExpression: "sum(xmidt_caduceus_outgoing_queue_depths) by (url)"
  metricsURL: "http://caduceator:5010/events"
  auth: ""
  timeout:

secret:
  header: "X-Webpa-Signature"
  delimiter: "="

webhook:
  registrationInterval: "24h"
  timeout: "5s"
  registrationURL: ""
  webhookCount: 1
  request:
    webhookConfig:
      url: ""
      # failureURL: "http://caduceator:5010/cutoff"
      secret: ""
      maxRetryCount: 3
      #AlternativeURLs: []
    events: "device-status.*"

  basic: "Basic dXNlcjpwYXNz"
  # jwt:
  #   # requestHeaders are added to the request for the token.
  #   # (Optional)
  #   requestHeaders:
  #     # - "":""
  #   # authURL is the URL to access for the token.
  #   authURL: ""
  #   # timeout is how long the request to get the token will take before
  #   # timing out.
  #   timeout: "1m"
  #   # buffer is the length of time before a token expires to get a new token.
  #   # (Optional)
  #   buffer: "1m"
